spring:
  application:
    name: productservice
  config:
    import: optional:file:/.env[.properties]

server:
  port: ${PRODUCT_SERVICE_PORT}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:DEBUG}
  file:
    path: ${LOG_FOLDER:/tmp}