spring:
  application:
    name: locale-bundles
  config:
    import: optional:file:/.env[.properties]

server:
  port: ${LOCAL_BUNDLES_SERVICE_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:DEBUG}
  file:
    path: ${LOG_FOLDER:/tmp}