services:
  postgres:
    image: postgres:latest
    container_name: postgres-auth2service
    environment:
      POSTGRES_DB: ${DB_POSTGRESQL_DATABASE_NAME}
      POSTGRES_USER: ${DB_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRESQL_PASSWORD}
    ports:
      - ${DB_POSTGRESQL_PORT_EXTERNAL}:${DB_POSTGRESQL_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_POSTGRESQL_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - online-store-auth2-network

  auth2service:
    image: auth2service
    build:
      context: .
      args:
        LOG_FOLDER: ${LOG_FOLDER}
        AUTH2_SERVICE_PORT: ${AUTH2_SERVICE_PORT}
    env_file:
      - .env
    environment:
      - AUTH2_SERVICE_PORT=${AUTH2_SERVICE_PORT}
      - LOG_FOLDER=${LOG_FOLDER}
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${DB_POSTGRESQL_PORT}/${DB_POSTGRESQL_DATABASE_NAME}
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://postgres:${DB_POSTGRESQL_PORT}/${DB_POSTGRESQL_DATABASE_NAME}
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=io.r2dbc.postgresql.PostgresqlConnectionFactory
      - SPRING_DATASOURCE_USERNAME=${DB_POSTGRESQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_POSTGRESQL_PASSWORD}
      - SPRING_LIQUIBASE_CHANGELOG=classpath:db/changelog/changelog-master.yaml
    depends_on:
      - postgres
    ports:
      - ${AUTH2_SERVICE_PORT}:${AUTH2_SERVICE_PORT}
    container_name: auth2service
    networks:
      - online-store-auth2-network

networks:
  online-store-auth2-network:
    name: online-store-auth2-network
    driver: bridge
    attachable: true

volumes:
  postgres_data: